<?php
?>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Classes</title>

    <style>

      img{
          border: 7px double rgb(215, 151, 32); 
          border-radius: 10px;
        }

      div{
        color: rgb(18, 131, 148);
        background-color: azure;
      }

    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  </head>
  
  <body>

    <div class="container">

        <div class="container 1">

          <img src="./yoga class.jpg" class="d-block w-100" alt="yoga class">
            <h1>Yoga</h1>
              <p>Yoga is a Sanskrit word translated as “yoke” or “union.” To yoke means to draw together, to bind together; or to unite. Its aim is to yoke or create a union of the body, mind, soul, and universal consciousness. This process of uniting the physical, mental, emotional, and spiritual aspects of ourselves is what allows yogis to experience deep states of freedom, peace and self-realization.

               MY LATEST VIDEOS
              </p>

        </div>

        <div class="container 1">
            <img src="./weights lifter.jpg" class="d-block w-100" alt="woman lifting weights">
              <h1>Weight Lifting</h1>
                <p>Weightlifting is the sport or exercise of lifting barbells. It often refers to several distinctive activities, one of which is a form of exercise, weight training, and three others that are competitive sports, namely, Olympic weightlifting, powerlifting, and bodybuilding.Different forms of weightlifting have somewhat different purposes. Weight training is to develop the size and strength of skeletal muscles through using the force of gravity, in the form of weighted bars or dumbbells, to oppose the force generated by muscle contraction. Weight training is a form of exercise that can be used by athletes in many sports other than bodybuilding or Olympic weightlifting to prepare for competition; it can also be practiced by amateurs as part of an overall fitness regimen.

              </p>
        </div>

        <div class="container 1">
            <img src="./Cardio exercise.jpg" class="d-block w-100" alt="people doing cardio">
              <h1>Cardio</h1>
              <p>"Cardio," which is fitness slang for cardiovascular activity, may be one of the most important types of physical activity to do on the regular. To maintain health, the Centers for Disease Control and the American College of Sports Medicine recommend performing a minimum of 30 minutes of moderate-intensity cardio activity on most, if not all, days of the week.

                Cardio refers to any activity that increases heart rate and respiration while using large muscle groups repetitively and rhythmically. The root word "card," or "heart," provides a clue as to why this type of exercise is so important—by providing training that progressively challenges your most vital internal life support network, cardio can improve both the function and the performance of your heart, lungs and circulatory system.</p>
        </div>

    </div>
    <br>

    <a href="gymshark 3.html">Back</a>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </body>

</html>